algoritmo (exercicio02)
    caractere turno
    real  horas , v1,v2
    início
    escreva("Digite o turno (N ou D)")
    leia (turno)
    escreva("digite as horas trabalhadas")
    leia(horas)
    v1 = 45
    v2 = 37,50

    se (turno == "n" ou turno=="N"){
        escreva("o Salario é: R$"+ horas*v1 )
    }
    senao (turno == "d" ou turno=="D"){
        escreva ("o Salario é: R$" horas*v2)
    } 



        
    fim