algoritmo (exercicio03)
    real bolsa,tempo    
    início
    escreva("Digite aqui o valor de sua Bolsa")
    leia (bolsa)
    escreva("Digite aqui o tempo de seu estagio")
    leia(tempo)

    if (bolsa<750 e bolsa>950)
        escreva("Não Participará")
    senao se (tempo<=1)
        escreva("não Participará")    
    senao (tempo>=2)
        escreva ("Participara do treinamento")
   
        
    fim