algoritmo (exercicio_11)	
	inteiro	a,b,soma,sub,multi,di,resto
	
	inicio
	escreva("digite aqui o valor de a")
	leia(a)
	escreva("digite aqui o valor de b")
	leia(b)
	soma = a+b
	sub = a-b
	multi = a*b
	di= inteiro(a/b)
	resto = (a%b)
	escreva ("A soma dos numeros é:"+ soma + "a Subtração dos numeros é: " + sub + "a Multiplicação dos é: "+ multi + "a Divisão dos numeros é: " + di + "o resto da divisão é: " + resto)
	
	fim
	