algoritmo exercicio01
    real entrada,custo,convites
    início
        escreva("Digite o custo para realização da peça: ");
        leia(custo);
        escreva("Digite o valor do ingresso: ");
        leia(entrada);
        convites = custo/entrada;
        escreva ("Para que a peça ao menos se pague, precisam ser vendidos pelo menos: "+ convites + " ingressos");  
    fim
	
	
	FERNANDO HENRIQUE DOS SANTOS RGM 28232437