algoritmo exercicio04
    inteiro senhaUsu,correta
    início
    escreva("Digite a senha (XXXX)")
    leia(senhaUsu)
    correta= 4531
    imrimeDados(inteiro senhaUsu,inteiro correta)
    fim
    
    void imrimeDados(inteiro senhaUsu,inteiro correta)
    inicio
        se(senhaUsu == correto){
            escreva("ACESSO LIBERADO")
        }
        senao 
            escreva("ACESSO NEGADO")
            
    fim